### ISSUE TITLE
Do this extension work on Windows ?

### ISSUE THREAD

**Issue by Tum1370** [Anglebrackets/web_rag#2]
I have installed the extension in to oobabooga.
I can see the extension at the bottom of the oobabooga chat window.
But when i try and use "get https://www.sciencedaily.com/releases/2024/01/240123175550.htm" the ai does not do anything or return anything,

I do not have 'links' browser installed ? IS that a Linux browser ?

**Comment by gladiattor666** [comment]
> I have installed the extension in to oobabooga. I can see the extension at the bottom of the oobabooga chat window. But when i try and use "get https://www.sciencedaily.com/releases/2024/01/240123175550.htm" the ai does not do anything or return anything,
> 
> I do not have 'links' browser installed ? IS that a Linux browser ?

I'm no expert but it seems made for linux only. Using Chat GPT I was able to fix it, now it runs on windows. Remember to also add the required librairies to the venv / miniconda.

**Comment by Tum1370** [comment]
How did you fix it please ?

**Comment by gladiattor666** [comment]
Here's the python code.
Make a backup of the original then replace it.
Remember it might need some librairies on the env of ooba.

`import gradio as gr
import pickle
from modules import chat, shared
from modules.chat import generate_chat_prompt
import os
import urllib.parse

try:
    print("TRY")
    with open('rag_txt_data.pkl', 'rb') as f:
        params = pickle.load(f)
except FileNotFoundError:
    print("EXCEPT")
    params = {
        "file_path": "c:\dummystuff.txt",
        "display_name": "Web RAG",
        "activate": True,
        "use_kay": False,
        "url":      "https://lite.duckduckgo.com/lite/?q=%q",
        "start":    "*start*",
        "end":      "*end*",
        "max":      "5000",
        "auto_key": "mytxt,",
        "data":     "",
    }
params.update({
        "auto_key": "mytxt,", 
        # "data":     "",        
})

def get_search_context(file_path, query):
    """
    Retrieve context from a specified file based on the given query. If no query, use parameters to find a specific section.
    """
    print("get_search_context")
    clear1()
    with open(file_path, 'r', encoding='utf-8') as file:
        content = file.read()
        num_characters = len(content)
        print("Number of characters in the file:", num_characters)
        
    if len(query) > 0:
        query_position = content.lower().find(query.lower())
        if query_position != -1:
            start_position = query_position
        else:
            start_position = 0
    else:
        start_position = 0

    if len(params['start']) > 0:
        start_index = content.find(params['start'], start_position)
        if start_index != -1:
            start_position = start_index + len(params['start'])

    end_position = len(content)
    if len(params['end']) > 0:
        end_index = content.find(params['end'], start_position)
        if end_index != -1:
            end_position = end_index

    if 'max' in params:
        max_length = int(params['max'])
        if start_position + max_length < end_position:
            end_position = start_position + max_length

    return content[start_position:end_position]

def save():
    print("save")
    with open('rag_txt_data.pkl', 'wb') as f:
        pickle.dump(params, f)

def clear1():
    params.update({'data': ""})
    save()
    return ""


def custom_generate_chat_prompt(user_input, state, **kwargs):
    """
    Only used in chat mode. Now fetches data from a specified local text file instead of the web.
    """
    user_prompt = user_input
    print("custom_generate_chat_prompt")
    if params['activate']:
        retrieved = ""
        parts = user_prompt.split(" ", 1)
        if len(parts) > 1:
            key = parts[0]
            if params['use_kay'] and key.lower() == params['auto_key'].lower():
                print("auto_key")
                user_prompt = parts[1].strip()
                retrieved = get_search_context(params['file_path'], user_prompt)
                data = params['data'] + retrieved
                context = data + state['context']
                state.update({'context': context})
            if not params['use_kay']:
                print("no auto_key")
                user_prompt = user_prompt
                retrieved = get_search_context(params['file_path'], user_prompt)
                data = params['data'] + retrieved
                context = data + state['context']
                state.update({'context': context})
        if len(retrieved) > 0:
            print(f"Retrieved {len(retrieved)}, total:{len(data)}")
            params.update({'data': data})
            save()
    result = chat.generate_chat_prompt(user_prompt, state, **kwargs)
    return result

def ui():
    """
    Gets executed when the UI is drawn. Custom gradio elements and
    their corresponding event handlers should be defined here.

    To learn about gradio components, check out the docs:
    https://gradio.app/docs/
    """
    print("UI")
    with gr.Accordion("TXT Retrieval-Augmented Generation - Retrieve data from TXT file and insert into context", open=True):
        with gr.Row():
            activate = gr.Checkbox(value=params['activate'], label='Activate TXT RAG')
            use_kay = gr.Checkbox(value=params['use_kay'], default=False, label='Use key.')
        with gr.Accordion("Key config", open=False):
            with gr.Row():
                with gr.Column():
                    key = gr.Textbox(value=params['auto_key'], label="Enter a key at the beginning of the prompt (not case sensitive). "
                                                                     "Retrieved data is kept into the context of all following prompts, "
                                                                     "until the 'Clear Data' button is pressed. Key text at start of prompt that invokes Auto-RAG. "
                                                                     "Not case-sensitive. When invoked, the remainder of the prompt is inserted into the url template below, "
                                                                     "results retrieved and then the prompt is processed normally with the retrieved context.")
        file_path = gr.Textbox(value=params['file_path'], label='Full windows path to the TXT file')
        with gr.Row():
            start = gr.Textbox(value=params['start'], label='Start: Retrieved data capture starts after this text is found (starts at beginning if not found)')
            end = gr.Textbox(value=params['end'], label='End: Retrieved data capture ends when this text is found (overrides maximum characters if found)')
            maxchars = gr.Number(value=params['max'], label='Maximum characters of retrieved data to keep (if end text not found)')
        with gr.Accordion("Edit retrieved data", open=False):
            with gr.Row():
                edit = gr.Button("Show Data", elem_classes='refresh-button')
                clear = gr.Button("Clear Data", elem_classes='refresh-button')
            retrieved = gr.Textbox(value=params['data'], label='Retrieved data')

    def update_activate(x):
        params.update({'activate': x})
        save()
    def update_use_kay(x):
        params.update({'use_kay': x})
        save()
        pass
    def update_maxchars(x):
        params.update({'max': x})
        save()
    def update_start(x):
        params.update({'start': x})
        save()
    def update_end(x):
        params.update({'end': x})
        save()
    def update_file_path(x):
        params.update({'file_path': x})
        save()
    def update_key(x):
        params.update({'auto_key': x})
        save()
    def clear_clicked(button_input):
        params.update({'data': ""})
        save()
        return ""
    def edit_clicked(button_input):
        data = params['data']
        return data
    def update_retrieved(x):
        print("retrieved update")
        params.update({'data': x})
        save()

    activate.change(update_activate, activate, None)
    use_kay.change(update_use_kay, use_kay, None)
    file_path.change(update_file_path, file_path, None)
    maxchars.change(update_maxchars, maxchars, None)
    key.change(update_key, key, None)
    start.change(update_start, start, None)
    end.change(update_end, end, None)
    clear.click(clear_clicked, clear, retrieved)
    edit.click(edit_clicked, edit, retrieved)
    retrieved.change(update_retrieved, retrieved, None)`

**Comment by gladiattor666** [comment]
Here's the python code.
This works on windows.
Remember it needs some extra librairies to work, you need to manually install this, e.g. beautiful soup.
It currently works on the latest up to date ooba.
Make a backup of the original code, then replace it with this one.

`import requests
import gradio as gr
import pickle
from modules import chat, shared
from modules.chat import generate_chat_prompt
import os
from bs4 import BeautifulSoup
import urllib.parse


try:
    with open('web_rag_data.pkl', 'rb') as f:
        params = pickle.load(f)
except FileNotFoundError:
    params = {
        "display_name": "Web RAG",
        "activate": False,
        "get_key":  "get",
        "url":      "https://lite.duckduckgo.com/lite/?q=%q",
        "start":    "[ Next Page > ]",
        "end":      "\n6.   ",
        "max":      "5000",
        "auto_key": "web,",
        "data":     "",
    }
params.update({
        "get_key":  "get",
        "auto_key": "web,",
})
def get_search_context(url, query):
    clear1()
    if len(query) > 0:
        print(f"query={query}")
        query = urllib.parse.quote_plus(query)
        if url.find('%q') >= 0:
            url = url.replace('%q', query)
    print(f"get_search_context: url={url}")
    
    response = requests.get(url)
    response.raise_for_status()  # Will raise HTTPError for bad requests (4XX or 5XX)

    # Use BeautifulSoup to parse HTML content and extract text
    soup = BeautifulSoup(response.text, 'html.parser')
    text = soup.get_text()
    
    # Finding specific start and end locations in the text, if required
    if len(params['start']) > 0:
        start = text.find(params['start'])
        if start < 0:
            start = 0
        else:
            start = start + 15
        text = text[start:]
    if len(params['end']) > 0:
        end = text.find(params['end'])
        if end < 0:
            end = int(params['max'])
    else:
        end = int(params['max'])
    text = text[:end]
    return text

def save():
    with open('web_rag_data.pkl', 'wb') as f:
        pickle.dump(params, f)

def clear1():
    params.update({'data': ""})
    save()
    return ""

def custom_generate_chat_prompt(user_input, state, **kwargs):
    """
    Only used in chat mode.
    """
    user_prompt = user_input
    if params['activate']:
        retrieved = ""
        parts = user_prompt.split(" ", 1)
        if len(parts) > 1:
            key = parts[0]
            if key.lower() == params['auto_key'].lower():
                user_prompt = parts[1].strip()
                retrieved = get_search_context(params['url'], user_prompt)
            elif key.lower() == params['get_key'].lower():  # url in prompt
                url = parts[1].strip()
                retrieved = get_search_context(url, "")
                total = len(retrieved) + len(params['data'])
                user_prompt = f'Say "Retrieved {len(retrieved)} characters." and "Total is {total}".'
        data = params['data'] + retrieved
        if len(retrieved) > 0:
            print(f"Retrieved {len(retrieved)}, total:{len(data)}")
            params.update({'data': data})
            save()
        context = data + state['context']
        state.update({'context': context})
    result = chat.generate_chat_prompt(user_prompt, state, **kwargs)
    return result

def ui():
    """
    Gets executed when the UI is drawn. Custom gradio elements and
    their corresponding event handlers should be defined here.

    To learn about gradio components, check out the docs:
    https://gradio.app/docs/
    """
    with gr.Accordion("Web Retrieval-Augmented Generation - Retrieve data from web pages and insert into context", open=True):
        activate = gr.Checkbox(value=params['activate'], label='Activate Web RAG')
        with gr.Accordion("Enter one of these keys at the beginning of the prompt (not case sensitive). Retrieved data is accumulated and inserted into the context of all following prompts, until the 'Clear Data' button is pressed.", open=True):
            with gr.Row():
                with gr.Column():
                    key = gr.Textbox(value=params['auto_key'], label="AUTO: Key text at start of prompt that invokes Auto-RAG. Not case-sensitive. When invoked, the remainder of the prompt is inserted into the url template below, results retrieved and then the prompt is processed normally with the retrieved context.")
                    url = gr.Textbox(value=params['url'], label='URL template: url-encoded prompt will replace %q')
                get_key = gr.Textbox(value=params['get_key'], label="DIRECT: Key text at start of prompt that invokes direct page retrieval.  The url to retrieve must follow this key in the prompt.")
        with gr.Row():
            start = gr.Textbox(value=params['start'], label='Start: Retrieved data capture starts after this text is found (starts at beginning if not found)')
            end = gr.Textbox(value=params['end'], label='End: Retrieved data capture ends when this text is found (overrides maximum characters if found)')
            maxchars = gr.Number(value=params['max'], label='Maximum characters of retrieved data to keep (if end text not found)')
        with gr.Accordion("Edit retrieved data", open=True):
            with gr.Row():
                edit = gr.Button("Show Data", elem_classes='refresh-button')
                clear = gr.Button("Clear Data", elem_classes='refresh-button')
            retrieved = gr.Textbox(value=params['data'], label='Retrieved data')

    def update_activate(x):
        params.update({'activate': x})
        save()
    def update_get_key(x):
        params.update({'get_key': x})
        save()
    def update_maxchars(x):
        params.update({'max': x})
        save()
    def update_start(x):
        params.update({'start': x})
        save()
    def update_end(x):
        params.update({'end': x})
        save()
    def update_url(x):
        params.update({'url': x})
        save()
    def update_key(x):
        params.update({'auto_key': x})
        save()
    def clear_clicked(button_input):
        params.update({'data': ""})
        save()
        return ""
    def edit_clicked(button_input):
        data = params['data']
        return data
    def update_retrieved(x):
        params.update({'data': x})
        save()

    activate.change(update_activate, activate, None)
    get_key.change(update_get_key, get_key, None)
    url.change(update_url, url, None)
    maxchars.change(update_maxchars, maxchars, None)
    key.change(update_key, key, None)
    start.change(update_start, start, None)
    end.change(update_end, end, None)
    clear.click(clear_clicked, clear, retrieved)
    edit.click(edit_clicked, edit, retrieved)
    retrieved.change(update_retrieved, retrieved, None)`

**Comment by Tum1370** [comment]
Thanks but that still creates errors for me..
I fxed the indentations of the script. BUt then i still have another error.
I installed beautiful suop4 library.

Does anything else need installing ?

**Comment by gladiattor666** [comment]
Can you show me the errors please ?

**Comment by Tum1370** [comment]
HI, I have just reinstalled it to get the error message for you. 
Here is the message i get after using your script.

Traceback (most recent call last):
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\modules\extensions.py", line 37, in load_extensions
    extension = importlib.import_module(f"extensions.{name}.script")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\installer_files\env\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\extensions\web_rag\script.py", line 167, in <module>
    activate.change(update_activate, activate, None)
    ^^^^^^^^
NameError: name 'activate' is not defined

**Comment by Tum1370** [comment]
ok i put those errors in to Meta AI, and ask for a fix.
This is what Meta AI sent as the fix.
I Had to define  activate inside the def ui function.

def ui():
    """
    Gets executed when the UI is drawn. Custom gradio elements and
    their corresponding event handlers should be defined here.

    To learn about gradio components, check out the docs:
    https://gradio.app/docs/
    """
    with gr.Accordion("Web Retrieval-Augmented Generation - Retrieve data from web pages and insert into context", open=True):
        activate = gr.Checkbox(value=params['activate'], label='Activate Web RAG')
        with gr.Accordion("Enter one of these keys at the beginning of the prompt (not case sensitive). Retrieved data is accumulated and inserted into the context of all following prompts, until the 'Clear Data' button is pressed.", open=True):
            with gr.Row():
                with gr.Column():
                    key = gr.Textbox(value=params['auto_key'], label="AUTO: Key text at start of prompt that invokes Auto-RAG. Not case-sensitive. When invoked, the remainder of the prompt is inserted into the url template below, results retrieved and then the prompt is processed normally with the retrieved context.")
                    url = gr.Textbox(value=params['url'], label='URL template: url-encoded prompt will replace %q')
                get_key = gr.Textbox(value=params['get_key'], label="DIRECT: Key text at start of prompt that invokes direct page retrieval.  The url to retrieve must follow this key in the prompt.")
        with gr.Row():
            start = gr.Textbox(value=params['start'], label='Start: Retrieved data capture starts after this text is found (starts at beginning if not found)')
            end = gr.Textbox(value=params['end'], label='End: Retrieved data capture ends when this text is found (overrides maximum characters if found)')
            maxchars = gr.Number(value=int(params['max']), label='Maximum characters of retrieved data to keep (if end text not found)')
        with gr.Accordion("Edit retrieved data", open=True):
            with gr.Row():
                edit = gr.Button("Show Data", elem_classes='refresh-button')
                clear = gr.Button("Clear Data", elem_classes='refresh-button')
            retrieved = gr.Textbox(value=params['data'], label='Retrieved data')

    activate.change(fn=update_activate, inputs=activate, outputs=None)
    get_key.change(fn=update_get_key, inputs=get_key, outputs=None)
    url.change(fn=update_url, inputs=url, outputs=None)
    maxchars.change(fn=update_maxchars, inputs=maxchars, outputs=None)
    key.change(fn=update_key, inputs=key, outputs=None)
    start.change(fn=update_start, inputs=start, outputs=None)
    end.change(fn=update_end, inputs=end, outputs=None)
    clear.click(fn=clear_clicked, inputs=clear, outputs=retrieved)
    edit.click(fn=edit_clicked, inputs=edit, outputs=retrieved)
    retrieved.change(fn=update_retrieved, inputs=retrieved, outputs=None)

**Comment by Tum1370** [comment]
Now with this bit adjusted, the web rag function loads up without errors, and shows me the ui below my chat window.
I then disabled all other extensions, so i could test the Web Rag extension.
And i copied and pasted the command from the Instructions.

get https://www.sciencedaily.com/releases/2024/01/240123175550.htm

this then produced new errors in my console.


Traceback (most recent call last):
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\queueing.py", line 580, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1928, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1526, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\utils.py", line 657, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\utils.py", line 650, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 2505, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 1005, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\utils.py", line 633, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\utils.py", line 816, in gen_wrapper
    response = next(iterator)
               ^^^^^^^^^^^^^^
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\modules\chat.py", line 443, in generate_chat_reply_wrapper
    for i, history in enumerate(generate_chat_reply(text, state, regenerate, _continue, loading_message=True, for_ui=True)):
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\modules\chat.py", line 410, in generate_chat_reply
    for history in chatbot_wrapper(text, state, regenerate=regenerate, _continue=_continue, loading_message=loading_message, for_ui=for_ui):
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\modules\chat.py", line 346, in chatbot_wrapper
    prompt = apply_extensions('custom_generate_chat_prompt', text, state, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\modules\extensions.py", line 231, in apply_extensions
    return EXTENSION_MAP[typ](*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\modules\extensions.py", line 107, in _apply_custom_generate_chat_prompt
    return extension.custom_generate_chat_prompt(text, state, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\extensions\web_rag\script.py", line 87, in custom_generate_chat_prompt
    retrieved = get_search_context(url, "")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\extensions\web_rag\script.py", line 40, in get_search_context
    response.raise_for_status()  # Will raise HTTPError for bad requests (4XX or 5XX)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.sciencedaily.com/releases/2024/01/240123175550.htm

**Comment by gladiattor666** [comment]
You can download the script here : https://www.swisstransfer.com/d/c8d42e97-0890-41e0-b33d-474fa5bcb72a

I'm getting the same error with your URL.
Your URL / server https://www.sciencedaily.com/releases/2024/01/240123175550.htm doesnt allow the script to get stuff.
Try the default one https://en.wikipedia.org/wiki/Charles_Martel

Some screenshots :
https://ibb.co/f2cBQbY
https://ibb.co/Cwt8mgq
https://ibb.co/8nkpXJ6

**Comment by Tum1370** [comment]
Thank you, That works good.
Yes it seems my script was working the same as well, but that one page from the readme of this extension was causing the isssue.
I can now enter a url, then ask questions about it.

Did you test if 5000 characters is the limit or can we increase that if needed ?
Can we load more than one webpage, or do we always have to clear data before loading a new page etc ?

**Comment by gladiattor666** [comment]
Glad it works for you now 👍
This is so useful !

Oh yeah you can go higher I went like 50 000 and it worked like a charm.
The limit is the model context not the webrag script. So you'll need to check the context of your model and setup this.

It can only load one page for each time you press the generate button but you can change the URL for the next one, but loosing the previous one. "Superbooga" might be something to explore if you need more than one URL, but I never get it working correctly. It does vectore storage like a database fashion ..... Have fun my friend.

**Comment by Mozard40** [comment]
🚀 AMÉLIORATIONS APPORTÉES

Meilleur User-Agent Headers complets pour ressembler à un vrai navigateur
Moins de risques de blocage 403

Gestion d'Erreurs Améliorée Messages de debug clairs
Gestion spécifique des erreurs requests

Nettoyage du Texte Optimisé Suppression des balises inutiles
Formatage proche de links -dump

Logs Détaillés ✅ Succès: X caractères récupérés
❌ Erreur requests: [détail]

❌ Erreur générale: [détail]

Voici la fonction :

def get_search_context(url, query): if len(query) > 0: print(f"query={query}") query = urllib.parse.quote_plus(query) if url.find('%q') >= 0: url = url.replace('%q', query) print(f"get_search_context: url={url}")


# APPROCHE AMÉLIORÉE ✅
try:
    import requests
    from bs4 import BeautifulSoup
    
    # Headers pour éviter le blocage
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
        'Accept-Language': 'fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3',
        'Accept-Encoding': 'gzip, deflate, br',
        'DNT': '1',
        'Connection': 'keep-alive',
        'Upgrade-Insecure-Requests': '1',
    }
    
    # Effectue la requête HTTP GET avec timeout
    response = requests.get(url, headers=headers, timeout=20)
    response.raise_for_status()  # Vérifie les erreurs HTTP
    
    # Utilise BeautifulSoup pour extraire le texte comme 'links -dump'
    soup = BeautifulSoup(response.content, 'html.parser')
    
    # Supprime les éléments non désirés
    for element in soup(['script', 'style', 'nav', 'header', 'footer', 'aside']):
        element.decompose()
    
    # Extrait le texte et nettoie
    text = soup.get_text()
    
    # Nettoyage avancé (comme links -dump)
    lines = (line.strip() for line in text.splitlines())
    chunks = (phrase.strip() for line in lines for phrase in line.split("  "))
    search_context = '\n'.join(chunk for chunk in chunks if chunk)
    
    print(f"✅ Succès: {len(search_context)} caractères récupérés")
    
except requests.exceptions.RequestException as e:
    print(f"❌ Erreur requests: {e}")
    search_context = f"Erreur de requête: {str(e)}"
except Exception as e:
    print(f"❌ Erreur générale: {e}")
    search_context = f"Erreur: {str(e)}"

# Le reste du code original pour le filtrage
if len(params.get('start', '')) > 0:
    start = search_context.find(params['start'])
    if start < 0:
        start = 0
    else:
        start = start + len(params['start'])
    search_context = search_context[start:]

if len(params.get('end', '')) > 0:
    end = search_context.find(params['end'])
    if end < 0:
        end = int(params.get('max', 2000))
else:
    end = int(params.get('max', 2000))

search_context = search_context[:end]
return search_context
